# -*- coding: utf-8 -*-
"""Movie Genre

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Hr-wR6hxLNRDS7FGBJpACiDVEUI8PP4
"""

import os
import re
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Step 1: Check files and load the datasets
train_path = "train_data.txt"
test_path = "test_data.txt"

if not os.path.exists(train_path) or not os.path.exists(test_path):
    print("Error: Missing dataset files in the sidebar menu.")
    print("Please upload both train_data.txt and test_data.txt before running.")
else:
    print("Dataset files found. Loading data into dataframes...")

    # Read training file with triple colon separator
    train_df = pd.read_csv(
        train_path,
        sep=":::",
        engine="python",
        names=["id", "title", "genre", "description"],
        header=None
    )

    # Read test file (note that it does not contain a genre column)
    test_df = pd.read_csv(
        test_path,
        sep=":::",
        engine="python",
        names=["id", "title", "description"],
        header=None
    )

    # Clean leading and trailing whitespaces from strings
    train_df["genre"] = train_df["genre"].str.strip()
    train_df["description"] = train_df["description"].str.strip()
    test_df["description"] = test_df["description"].str.strip()

    print("Data successfully loaded.")
    print("Total training records:", len(train_df))
    print("Total testing records:", len(test_df))

    # Step 2: Set up the text cleaning function
    nltk.download('stopwords', quiet=True)
    stop_words_list = set(stopwords.words('english'))

    def clean_movie_description(text_input):
        if not isinstance(text_input, str):
            return ""

        # Convert text to lowercase
        text_lower = text_input.lower()

        # Remove punctuation, numbers, and symbols
        text_letters_only = re.sub(r'[^a-z\s]', '', text_lower)

        # Split string into individual words
        words_tokenized = text_letters_only.split()

        # Remove standard english stop words
        filtered_words = [w for w in words_tokenized if w not in stop_words_list]

        # Combine remaining words back into a single text string
        return " ".join(filtered_words)

    print("Starting text preprocessing layer...")

    # Apply cleaning process to description columns
    train_df["clean_description"] = train_df["description"].apply(clean_movie_description)
    test_df["clean_description"] = test_df["description"].apply(clean_movie_description)

    print("Text preprocessing completed.")

    # Step 3: Numerical Feature Extraction (TF-IDF Vectorization)
    print("Converting text features into numerical vectors...")

    # Limiting features to a standard cap to maintain memory safety
    tfidf_model = TfidfVectorizer(max_features=10000, max_df=0.95)

    x_train_text = train_df["clean_description"]
    y_train_labels = train_df["genre"]

    # Fit vectorizer and transform the processed training texts
    x_train_vectors = tfidf_model.fit_transform(x_train_text)

    print("Vocabulary matrix constructed. Total feature dimensions:", x_train_vectors.shape[1])

    # Step 4: Model Initialization and Training
    print("Training Logistic Regression classifier on the vector space...")

    # Standard linear multi-class parameters matching standard internship scopes
    classifier_engine = LogisticRegression(C=2.0, max_iter=200, solver='liblinear')
    classifier_engine.fit(x_train_vectors, y_train_labels)

    print("Model training successfully completed.")

    # Step 5: Evaluate Model Predictions on Unseen Test Dataset
    print("Vectorizing testing dataset instances...")
    x_test_vectors = tfidf_model.transform(test_df["clean_description"])

    print("Running evaluation predictions across testing variables...")
    test_predictions = classifier_engine.predict(x_test_vectors)

    # Map predictions back to the test dataframe
    test_df["predicted_genre"] = test_predictions

    print("Testing data evaluation complete. Reviewing first 5 prediction rows:")
    print("----------------------------------------------------------------")
    print(test_df[["title", "predicted_genre"]].head(5))
    print("----------------------------------------------------------------\n")

    # Step 6: Interactive Tester Framework for Custom User Input
    def evaluate_custom_plot_string(custom_plot_input):
        # Process custom text input using the same cleaning logic
        cleaned_custom_plot = clean_movie_description(custom_plot_input)

        # Convert text to matching sparse vector matrix shape
        vectorized_custom_plot = tfidf_model.transform([cleaned_custom_plot])

        # Run calculation through the trained classifier
        predicted_output_genre = classifier_engine.predict(vectorized_custom_plot)[0]

        print("Custom User Test Execution:")
        print("Input Summary text:", custom_plot_input)
        print("Predicted Category result:", predicted_output_genre.upper())
        print("----------------------------------------------------------------\n")

    # Call custom test routine with a sample plot string to verify functionality
    evaluate_custom_plot_string("A rogue astronaut discovers an ancient alien spaceship hidden in the dark rings of Saturn.")